### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jimaek** [jimaek/akulov.com#1]

**Comment by jimaek** [comment]
@globalping traceroute jsdelivr.com

**Comment by globalping** [comment]
Unknown endpoint. Example 'ping 1.2.3.4 from Germany'

**Comment by jimaek** [comment]
@globalping help

**Comment by globalping** [comment]
The Globalping bot is a simple interface to interact with the Globalping API and run global networking tests. Need a traceroute done from Japan? Or check the ping latency of an endpoint from Brazil? Just ask me!

*Manual*
The Globalping Bot follows a similar format to the CLI but it's more human friendly. It currently supports only the traceroute and ping commands. 
```
@globalping {command} {endpoint} from {city or country or continent or region or US state or ASN or ISP name} limit {how many results you want to get}
e.g. 
ping google.com from New York
traceroute 1.2.3.4 from Europe limit 2
ping 1.2.3.4 from AS80085
```

**Comment by jimaek** [comment]
@globalping traceroute jsdelivr.com from world

**Comment by globalping** [comment]
EU, CZ, Prague, ASN:204957
```
traceroute to jsdelivr.com (216.24.57.253), 20 hops max, 60 byte packets
 1  gw.ipv4.layer6.net (62.233.57.1)  0.222 ms  0.250 ms
 2  vl442.cr3.r1-8.dc1.4d.prg.masterinter.net (81.31.40.73)  0.211 ms  0.264 ms
 3  po246.cr7.r1-8.dc1.4d.prg.masterinter.net (83.167.254.151)  0.308 ms  0.361 ms
 4  nix4.cloudflare.com (91.210.16.171)  7.424 ms  7.432 ms
 5  216.24.57.253 (216.24.57.253)  0.294 ms  0.346 ms
```

**Comment by globalping** [comment]
I couldn't understand you :( Try asking me for help

**Comment by jimaek** [comment]
@globalping http --latency google.com

**Comment by globalping** [comment]
Failed to process command `http --latency google.com`.
```
Parameter validation failed.
"target" is required
```
Documentation and Support: https://github.com/jsdelivr/globalping

**Comment by jimaek** [comment]
@globalping http --latency google.com from EU

**Comment by globalping** [comment]
Failed to process command `http --latency google.com from EU`.
```
Parameter validation failed.
"target" is required
```
Documentation and Support: https://github.com/jsdelivr/globalping

**Comment by jimaek** [comment]
@globalping http google.com --latency

**Comment by globalping** [comment]
Here are the results for `http google.com --latency`
>**NA, MX, Queretaro, ASN:31898, Oracle Corporation**
```
Total: 79 ms
Download: 1 ms
First byte: 51 ms
DNS: 26 ms
TLS: null ms
TCP: 1 ms
```
